[theme]
base = "light"              # ใช้โหมดสว่างเสมอ
primaryColor = "#ff6f91"    # สีหลัก (ชมพู) เช่น ช่อง checkbox, multiselect
backgroundColor = "#fff8f1" # สีพื้นหลัง
secondaryBackgroundColor = "#f3eefc"  # สีพื้นหลังของช่องกรอกข้อมูล
textColor = "#2b2350"       # สีตัวอักษร